# Generated by Django 4.1.7 on 2023-02-16 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 2, 16)),
        ),
    ]
